### ISSUE TITLE
how to solve Error: Command Failed problem

### ISSUE THREAD

**Issue by mohanzeal** [Mitranim/epdf#3]
Hello, Nice work. When I ran npm install -g epdf and execute epdf command below error is poping up. It is executing fine in local system. My local system has 8gb ram and i5 processor. My server is having 1gb ram and 1 core cpu. I am getting issue in the server. Is this anything related to low server specs?

```
{ Error: Command failed: /usr/local/lib/node_modules/epdf/node_modules/electron/dist/electron /usr/local/lib/node_modules/epdf/lib/epdf.js  --out="/tmp/epdf/474a04ae-1b27-4994-8881-88ae13682275.pdf"

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/epdf/node_modules/electron/dist/electron /usr/local/lib/node_modules/epdf/lib/epdf.js  --out="/tmp/epdf/474a04ae-1b27-4994-8881-88ae13682275.pdf"' }

```

**Comment by mitranim** [comment]
Looks like a documentation failure on my part. To run Electron on a server, you need a virtual display driver. Also make sure you have fonts for the entire Unicode range. Here's the crucial parts of our dockerfile:

```dockerfile
RUN apt-get update && \
  apt-get install apt-transport-https && \
  apt-get update && \
  apt-get install -y apt-utils xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic libxfont1 libnotify4 libxss1 libgtk2.0-0 libgconf-2-4 libnss3 libnotify-bin xfonts-wqy ttf-ancient-fonts fonts-arphic-ukai fonts-arphic-uming && \
  rm -rf /var/lib/apt/lists/*

ENV DISPLAY=':99.0'

CMD DEBUG=* xvfb-run -a --server-args="-screen 0 1280x1028x24 -ac +extension GLX +extension RANDR +render" node .
```

Should probably document this.

**Comment by mohanzeal** [comment]
hey thanks for the quick reply. i will definitely try this

**Comment by mohanzeal** [comment]
can you please provide the full Dockerfile. I am also trying to deploy using docker to my server. 
It will be very helpful

**Comment by mitranim** [comment]
```dockerfile
FROM node:7

ARG CONF

RUN apt-get update && \
  apt-get install apt-transport-https && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -y apt-utils yarn xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic libxfont1 libnotify4 libxss1 libgtk2.0-0 libgconf-2-4 libnss3 libnotify-bin xfonts-wqy ttf-ancient-fonts fonts-arphic-ukai fonts-arphic-uming imagemagick graphicsmagick && \
  rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production
ENV DISPLAY=':99.0'

COPY . /app

WORKDIR /app

RUN yarn install

# RUN Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

CMD DEBUG=* xvfb-run -a --server-args="-screen 0 1280x1028x24 -ac +extension GLX +extension RANDR +render" yarn run-pdf
```

**Comment by mohanzeal** [comment]
thanks alot i will definetely try this
